### ISSUE TITLE
Missing variables

### ISSUE THREAD

**Issue by camdagr8** [hemminger8/vw-starter-kit#5]
Looks like a lot of variables aren't defined in the .scss file pertaining to this block of code: 

```css
    // because of possible rounding, we make sure the font-size is correct at the layout sizes
    @media screen and (width: $layout-desktop) and (min-width: $desktop-min) and (max-width: $desktop-max),
    screen and (width: $layout-tablet) and (min-width: $tablet-min) and (max-width: $tablet-max),
    screen and (width: $layout-mobile) and (min-width: $mobile-min) and (max-width: $mobile-max) {
        font-size: $base-font-size;
    }
```

Makes it so you can't use it stand alone unless you comment that block out.
